module.exports = {
  modul: {
    axios: require("axios"),
    baileys: require("@whiskeysockets/baileys"),
    chalk: require("chalk"),
    cheerio: require("cheerio"),
    crypto: require("crypto"),
    fs: require("fs"),
    ffmpeg: require("fluent-ffmpeg"),
    figlet: require("figlet"),
    fsx: require("fs-extra"),
    keyeddb: require("@whiskeysockets/baileys"),
    moment: require("moment-timezone"),
    child_process: require("child_process"),
    path: require("path"),
    human: require("human-readable"),
    FileType: require("file-type"),
    pino: require("pino"),
    process: require("process"),
    parsems: require("parse-ms"),
    os: require("os"),
    speed: require("performance-now"),
    PhoneNumber: require("awesome-phonenumber"),
    util: require("util"),
    Utils: require("@whiskeysockets/baileys/lib/Utils"),
    webp: require("node-webpmux"),
  },
};
